---
- name: Ensure mount group exists
  ansible.builtin.group:
    name: "{{ mount_group }}"
    state: present

- name: Ensure the mount point directory exists
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"

- name: Ensure exfatprogs is installed
  ansible.builtin.package:
    name: exfatprogs
    state: present
  when: filesystem_type == "exfat"

- name: Add the external drive to fstab
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ device_name }}"
    fstype: "{{ filesystem_type }}"
    opts: "defaults,uid={{ mount_owner }},gid={{ mount_group }},umask={{ mount_umask }}"
    state: "mounted"
    backup: yes

- name: Ensure the external drive is mounted
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ device_name }}"
    fstype: "{{ filesystem_type }}"
    opts: "defaults,uid={{ mount_owner }},gid={{ mount_group }},umask={{ mount_umask }}"
    state: mounted

- name: Ensure the target directory for symlink exists
  ansible.builtin.file:
    path: "{{ symlink_path }}"
    state: directory
    mode: '0755'
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"

- name: Remove existing directory if exists at symlink path
  ansible.builtin.file:
    path: "{{ symlink_path }}"
    state: absent
  #when: ansible_facts['ansible_mounts'] | map(attribute='mount') | list | select('match', mount_point) | list | length == 1

- name: Create a symlink from the mount point to the symlink path
  ansible.builtin.file:
    src: "{{ mount_point }}{{ '/' + mount_subpath if mount_subpath is defined else '' }}"
    dest: "{{ symlink_path }}"
    state: link
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
