---
- name: Basic Ansible Playbook
  hosts: all
  become: yes
  roles:
    - ntp
    - artis3n.tailscale
    - systemd_watchdog
    - role: mount_drive
      vars:
        mount_point: /mnt/drive
        mount_subpath: Underholdning
        device_name: /dev/sda1
        filesystem_type: exfat
        symlink_path: /data/media
        mount_owner: automator
        mount_group: extmedia
    - hadrienpatte.jellyfin
    - role: sagikazarmark.qbittorrent_nox
      vars:
        qbittorrent_nox_user_groups:
          - extmedia
    - install_utilities
