---
- name: Basic Ansible Playbook
  hosts: all
  become: yes
  roles:
    - ntp
    - artis3n.tailscale
    - systemd_watchdog
    - install_utilities
    - role: mount_drive
      vars:
        mount_point: /mnt/drive
        mount_subpath: Underholdning
        device_name: /dev/sda1
        filesystem_type: exfat
        symlink_path: /data/media
        mount_owner: automator
        mount_group: extmedia
    - role: hadrienpatte.jellyfin
      vars:
        jellyfin_FQDN:
          - raspberrypi
    - role: add_user_to_group
      vars:
        user: jellyfin
        group: extmedia
    - role: sagikazarmark.qbittorrent_nox
      vars:
        qbittorrent_nox_user_groups:
          - extmedia
    - role: nickjj.docker
      tags: ["docker"]
    - role: setup_arr_suite
      vars:
        timezone: "Europe/Copenhagen"

        # PUID and PGID for each service
        bazarr_puid: 995
        bazarr_pgid: 1001
        prowlarr_puid: 1000
        prowlarr_pgid: 1001
        radarr_puid: 995
        radarr_pgid: 1001
        sonarr_puid: 995
        sonarr_pgid: 1001

        # Volume paths
        bazarr_config: "/data/media/Apps/bazarr/config"
        prowlarr_config: "/data/media/Apps/prowlarr/config"
        radarr_config: "/data/media/Apps/radarr/config"
        sonarr_config: "/data/media/Apps/sonarr/config"
        tv_shows_path: "/data/media/Serier"
        movies_path: "/data/media/Film"
        downloads_path: "/home/qbtuser/Downloads"
    - role: setup_auth
      vars:
        ldap_organisation: "Krestens Homelab"
        ldap_domain: "kresten.xyz"
        ldap_admin_password: "adminpassword"
        ldap_config_password: "configpassword"
    - role: sebdanielsson.cloudflared
      vars:
        cloudflare_tunnel_enable: true
      state: present
